# _config.yml
title: VietNam Quantum Computing Blog
description: Explore the Quantum World.
author: luongle1911
email: lephuluong1911@gmail.com
baseurl: "/vietnamquantumcomputing" # Set this to your repository name if your repo is NOT 'luongle1911.github.io'. If your repo IS 'luongle1911.github.io', set baseurl: "".
url: "https://luongle1911.github.io" # Your GitHub Pages URL

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax # This tells kramdown to use MathJax for math rendering
  math_engine_opts:
    preview: false # Optional: Disable MathJax previews if unnecessary
  # Optional: Some complex setups might need this if you face issues with MathJax v3:
  # math_engine_opts:
  #   chain_jax: false
theme: minima # You can choose other themes or create your own
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Recommended for SEO

paginate: 3 # Number of posts per page
paginate_path: "/page/:num/" # URL structure for paginated pages

# Exclude from processing.
# The following items will not be processed, by Jekyll.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor